### ISSUE TITLE
ComposeGuard invalidates all kotlin tasks when running `debugComposeCompilerCheck`

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#47]
This is semi-related to the recent changes, but I decided to create a new ticket instead.

When performing following steps:

1. `./gradlew compileDebugKotlin`
2. `./gradlew debugComposeCompilerCheck`

Second step should take like a second at most, since it only needs to compare generated txt file to the baseline. However, because [ComposeGuard changes kotlin tasks's configuration depending on which task is called](https://github.com/j-roskopf/ComposeGuard/blob/main/compose-guard/gradle-plugin/src/main/kotlin/com/joetr/compose/guard/ReportGenPlugin.kt#L240), it invalidates the kotlin task every time it is called, requiring it to be recompiled again.

This is an issue with CI setups. On our setup we first build the app and then we perform various static checks (including ComposeGuard) in the next step. Unfortunately, that means that ComposeGuard will force all compose-related kotlin code to be recompiled again on the check step.

This happens with both `2.2.1` and `2.2.4-alpha`

**Comment by j-roskopf** [comment]
I learned today that the compose compiler metrics are only generated for the files that were compiled

so in an incremental compilation scenario, metrics would only be generated for the files that were compiled and the remainder of the composables would not show up in the metrics

This is actually kind of a wild bug in compose guard right now that I verified in both 2.2.4-alpha and 2.2.1, but if you run generate task for a module, then add a new file with a new composable and run the generate task again, the metrics in `module/compose_reports` just contains the new composable 

so I don't know if it's entirely possible for the kotlin compile task to stay up to date in this scenario. 

I verified this behavior in a brand new project without compose guard where I just apply the parameters myself and saw the same behavior

```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>() {
    compilerOptions.freeCompilerArgs.addAll(
        "-P",
        "plugin:androidx.compose.compiler.plugins.kotlin:metricsDestination=${project.buildDir.absolutePath.plus("/").plus("newComposeReports")}",
    )
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>() {
    compilerOptions.freeCompilerArgs.addAll(
        "-P",
        "plugin:androidx.compose.compiler.plugins.kotlin:reportsDestination=${project.buildDir.absolutePath.plus("/").plus("newComposeReports")}",
    )
}
```

**Comment by j-roskopf** [comment]
With that in mind, I've pushed 2.2.6-alpha up to maven central that definitely makes some tradeoffs, but I think is the best foot forward for this plugin. 

I'm happy to help address any further issues though, but I may need to do some brain storming to work around some of the tradeoffs.

Thanks again for all of the reports! It's been tremendously helpful

**Comment by matejdro** [comment]
> I learned today that the compose compiler metrics are only generated for the files that were compiled

Huh that behavior is really not very good. Any chance we can create a ticket on the Kotlin issue tracker? Or do we just add a comment to the existing https://youtrack.jetbrains.com/issue/KT-70509?



I've tried steps from the first post and I can still reproduce them on the `2.2.6-alpha`. But on the other hand, with this broken incremental behaviour I really don't have any idea for a better way without removing dependency on the `gradle.startParameter.taskNames`.

However, how about this workaround?

```
composeGuardCheck {
   configureKotlinTasks = false
}
```

setting this flag to false, would completely prevent this plugin from touching configuration of any kotlin tasks. Then user of the plugin could manually configure `reportsDestination` to always point to the `build/compose_reports` folder, regardless of the `gradle.startParameter.taskNames`, which should solve this issue. It would break automatic baseline generation (user would have to copy the folder manually), but I consider that a good tradeoff for advanced users that prefer compiler performance over easy baseline generation.

**Comment by j-roskopf** [comment]
Created a ticket - https://youtrack.jetbrains.com/issue/KT-70878/Compose-metrics-are-only-generated-for-incrementally-compiled-Composable-code

I am definitely amenable to making it configurable. I have added support for this configuration

```
composeGuard { 
    configureKotlinTasks = false // defaults to true
}
```

With this set, the plugin no longer configures anything in the Kotlin compile task. So an end user would be responsible for generating the golden metrics and the check metrics before running the check task.

Will push that up in a 2.2.7-alpha

**Comment by matejdro** [comment]
Thank you!

If you are curious, this is how we do it now:

```kotlin
composeGuard {
   configureKotlinTasks = false
}

// List of all tasks in this module that compile compose stuff (excluding KSP etc.)
val composeCompileTasks = listOf("compileDebugKotlin", "compileReleaseKotlin")

val composeReportsFolder = composeGuardCheck.outputDirectory.get()
project.tasks.named { composeCompileTasks.contains(it) }.withType<KotlinCompile<*>>().configureEach {
   kotlinOptions {
      freeCompilerArgs += listOf(
         "-P",
         "plugin:androidx.compose.compiler.plugins.kotlin:reportsDestination=" +
            "$composeReportsFolder"
      )
      freeCompilerArgs += listOf(
         "-P",
         "plugin:androidx.compose.compiler.plugins.kotlin:metricsDestination=" +
            "$composeReportsFolder"
      )
   }

   outputs.dir(composeReportsFolder)
}

tasks.register<Copy>("generateComposeGuardBaseline") {
   from(composeReportsFolder)
   into(composeGuardGenerate.outputDirectory)

   dependsOn("compileDebugKotlin")
}
```

We always set the metrics and reports destination (so configuration does not change and invalidate anything when compose guard tasks are applied) and we have created our own baseline task that simply copies over folder from the build directory.

For now, we have not hit incremental issues yet, but I can report if we do.
